############## UHR-IonStar 1.3 ################

library("extrafont")
library("DO.db")
library("shiny")
library("shinydashboard")
library("DT")
library("knitr")
library("devtools")
library("ggplot2")
library("ggcorrplot")
library("ggbiplot")
library("reshape2")

library("limma")
library("TCGAbiolinks")
library("clusterProfiler")
library("AnnotationHub")
library("RDAVIDWebService")
library("IonStarStat")
library("ggrepel")


source("script/SourceCodes.R")
options(shiny.maxRequestSize=20000*1024^2)

  ### Define UI ----
  ui <- dashboardPage(
    dashboardHeader(title = "UHR-IonStar v1.3"),
    dashboardSidebar(
      sidebarMenu(
        menuItem("Homepage", tabName = "Homepage", icon = icon("home")),
        menuItem("IonStarStat", tabName = "IonStarStat", icon = icon("edit")),
        menuItem("Processing", tabName = "Process", icon = icon("edit")),
        menuItem("Visualization", tabName = "Visual", icon = icon("eye")),
        menuItem("Changes Discovery", tabName = "Biomarkers", icon = icon("filter")),
        menuItem('Re-verification', tabName = "Verify", icon = icon("check"))

      )
    ),
    dashboardBody(
      tags$head(
        tags$style(
          "body{
          min-height: 800px;
          height: auto;
          min-width: 1600px;
          margin: auto;
}"
      )
        ),

      tabItems(
        ##Homepage
        {
          tabItem(tabName = "Homepage",
                  fluidPage(
                    titlePanel(strong("UHR-IonStar")),
                    mainPanel(
                      img(src="logo.png",height=120,width=120),
                      p("UHR-IonStar is a Shiny-based interactive web app designed for processing, visualization and mining of quantitative proteomics data generated by IonStar."),
                      p("Fundamental components of UHR-IonStar include:"),
                      p(icon("check"),"Data cleanup"),
                      p(icon("check"),"Case-control ratio calculation and statistical testing"),
                      p(icon("check"),"Graphic depiction of quantitative results"),
                      p(icon("check"),"Basic data mining (e.g. Principle Component Analysis)"),
                      p(icon("check"),"DAVID-based Gene Ontology analysis"),
                      p("To get started, click on the blocks in left-side tab then upload files you want to process."),
                      p("Click the botton below to download the manual:"),
                      downloadButton("downloadManual", label="Download Manual", icon=icon("download")),
                      p("For questions, suggestions, and other relevant topics about UHR-IonStar, please contact the developers:"),
                      p("Shuo Qian:",
                        a("sqian@buffalo.edu",
                          href = "mailto:sqian@buffalo.edu")),
                      p("Shichen Shen:",
                        a("shichens@buffalo.edu",
                          href = "mailto:shichens@buffalo.edu")),
                      p("Jun Qu:",
                        a("junqu@buffalo.edu",
                          href = "mailto:junqu@buffalo.edu"))
                    )
                  )
          )},

        #IonStarStat
        {
          tabItem(tabName = "IonStarStat",
                 fluidPage(
                   titlePanel(strong("IonStarStat")),
                   sidebarLayout(
                     position = "left",
                     sidebarPanel(
                       h4(strong("Frames Generation:")),
                       fileInput("fileStat4", "Upload SEIVE database (.sdb)",
                                 accept=c(".sdb")),
                       fileInput("fileStat5", "Upload Spectrum report (.csv)",
                                 accept=c("text/csv",
                                          "text/comma-separated-values,text/plain",
                                          ".csv")),
                       actionButton(inputId = "goButtonStat3",label = "Submit database and spectrum report",icon=icon("pencil"),width="100%"),
                       br(),
                       textOutput("noticeStat3"),
                       br(),
                       h6(strong("Several settings in Spectrum report:")),
                       textInput(inputId = "filenumber",
                                 label = "Input the number of column which contains filename information:", value = "1"),
                       textInput(inputId = "scannumber",
                                 label = "Input the number of column which contains MS2 scan number:", value = "3"),
                       textInput(inputId = "proaccession",
                                 label = "Input the number of column which contains protein accessions:", value = "16"),
                       textInput(inputId = "pepseq",
                                 label = "Input the number of column which contains peptide sequence:", value = "15"),
                       actionButton(inputId = "goButtonStat4",label = "Generate Frames",icon=icon("pencil"),width="100%"),
                       helpText("A notaion will pop out after completion:"),
                       br(),
                       textOutput("noticeStat5"),
                       downloadButton("downloadDataStat2", label="Download Annotated Frame List", icon=icon("download")),
                       downloadButton("downloadDataStat3", label="Download Sample ID", icon=icon("download")),
                       br(),
                       tags$hr(),
                       h4(strong("Protein Quantification:")),
                       fileInput("fileStat6", "Upload Frame List(.csv)",
                                 accept=c("text/csv",
                                          "text/comma-separated-values,text/plain",
                                          ".csv")),
                       fileInput("fileStat7", "Upload Sample ID (.csv)",
                                 accept=c("text/csv",
                                          "text/comma-separated-values,text/plain",
                                          ".csv")),
                       actionButton(inputId = "goButtonStat5",label = "Submit Annotated Framelist and SampleID",icon=icon("pencil"),width="100%"),
                       br(),
                       textOutput("noticeStat6"),
                       br(),
                       checkboxGroupInput("Share_rm",
                                          "Choose whether you want to do remove shared peptides between different species:",
                                          choices = "Remove Shared Peptides"),
                       actionButton(inputId = "goButtonStat6",label = "Perform Protein Quantification",icon=icon("pencil"),width="100%"),
                       br(),
                       helpText("A notaion will pop out after completion:"),
                       textOutput("noticeStat8"),
                       downloadButton("downloadDataStat4", label="Download Quantification Data", icon=icon("download")),
                       downloadButton("downloadDataStat5", label="Download Peptides", icon=icon("download")),
                       br(),
                       tags$hr()

                     ),#sidebarpanel
                     mainPanel(
                       h3(strong("IonStarStat")),
                       textOutput("message1"),
                       textOutput("message2")
                     )
                     )#sidebarlayout
                   )#fieldpage
        )}, # tabItem

        #Data processing
        {tabItem(tabName = "Process",
                 fluidPage(
                   titlePanel(strong("Data Processing")),
                   sidebarLayout(
                     position = "left",
                     sidebarPanel(
                       fileInput("file1", "Upload quantitative results (.csv):",
                                 accept=c("text/csv",
                                          "text/comma-separated-values,text/plain",
                                          ".csv")),
                       fileInput("file2", "Upload group file (.csv):",
                                 accept=c("text/csv",
                                          "text/comma-separated-values,text/plain",
                                          ".csv")),
                       tags$hr(),
                       radioButtons("qpat","The pattern of the quantitative file:",
                                    c("Protein file"="pro",
                                      "Peptide file"="pep")),
                       actionButton(inputId = "goButton",label = "Submit",icon=icon("upload"),width="100%"),


                       br(),
                       tags$hr(),

                       helpText("Please fill in your control group shown in the right, case sensitive (default is the first one):"),
                       #  selectInput(inputId = "ctrlGroup", label = "Assign control group", choices = " "),
                       textInput(inputId = "ctrlGroup",
                                 label = "Assign control group", value="XXX"),
                       radioButtons("testing","Statistical testing method",
                                    c("Original t-test"="t",
                                      "Paired t-test"="paired-t")),
                       textInput("decoy", "Decoy Protein identifier",
                                 value="XXX"),
                       actionButton("calculate",label="Start Data Processing",icon=icon("pencil"),width="100%"),
                       br(),
                       helpText("A notaion will pop out after completion:"),
                       textOutput("notice1"),
                       downloadButton("downloadData", label="Download Processed Quantity Results", icon=icon("download")),
                       downloadButton("downloadData2", label="Download Average Ratios", icon=icon("download"),width="100%"),
                       downloadButton("downloadData_all", label="Download All Together", icon=icon("download"),width="100%"),
                       helpText("Note: Decoy entries and proteins with missing data will be removed automatically during the data processing step.")
                     ),
                     mainPanel(
                       h4(strong("Quantitative Results")),
                       DT::dataTableOutput("contents"),
                       textOutput("submitted")
                     )
                   )
                 )
        )}, # tabItem

        ##Data visualization
        {tabItem(tabName = "Visual",
                 fluidPage(
                   titlePanel(strong("Data Visualization")),
                   sidebarLayout(
                     position = "left",
                     sidebarPanel(
                       selectInput(inputId = "plotType",
                                   label = "Select plot type:",
                                   choices = c("Intra-group CV boxplot", "Protein intensity-rank curve", "Inter-group correlation plot",
                                               "Pearson correlation matrix plot","Principal Component Analysis (PCA)")),
                       p(strong("*For Pearson correlation plot ONLY:")),
                       helpText("Please fill the lower bound of Correlation value showing in the plot(number only):"),
                       textInput(inputId = "corr",
                                 label = "Correlation Lower Bound", value = "0.9"),
                       p(strong("*For Inter-group correlation plot ONLY:")),
                       helpText("Please fill in the groups you want to see, case sensitive ( Default is the first two groups):"),
                       textInput(inputId = "inter_group1",
                                 label = "Group 1", value = "XXX"),
                       textInput(inputId = "inter_group2",
                                 label = "Group 2", value = "XXX"),

                       actionButton("plot",label="Plot",icon=icon("paint-brush"),width="100%"),
                       p(strong("Plot saving options:")),
                       helpText("Recommends larger width and height values when plots for Pearson correlation matrix and PCA."),
                       sliderInput("sliderwid","Plot width",
                                   min = 4,max = 20,value = 6),
                       sliderInput("sliderhei","Plot height",
                                   min = 4,max = 20,value = 4),
                       #   checkboxGroupInput("exporttype","Export format",
                       #                       choices = list("Vector-PDF" = 1,
                       #                                      "Bitmap-PNG" = 2,
                       #                                      "Bitmap-TIFF" = 3)),
                       downloadButton("downloadPlot", label="Download Current Plot",
                                      icon=icon("download"),width="100%"),
                       br(),
                       h4(strong("Ratio distribution plots settings:")),
                       checkboxGroupInput("ratio_plot_selection",
                                          "Choose group/groups you want to show in ratio distribution plot:",
                                          choices = " ", selected = " "),
                       checkboxGroupInput("dist_correction",
                                          "Choose whether you want to do distribution correction:",
                                          choices = "Correction"),
                       actionButton("plot2",label="Plot for Ratio Distribution",
                                    icon=icon("paint-brush"),width="100%"),
                       sliderInput("sliderwid2","Plot width",
                                   min = 4,max = 20,value = 6),
                       sliderInput("sliderhei2","Plot height",
                                   min = 4,max = 20,value = 4),
                       downloadButton("downloadPlot2", label="Download Current Plot",
                                      icon=icon("download"),width="100%"),
                       downloadButton("downloadData4", label = "Download corrected ratio dataset",
                                      icon = icon("download"), width = "100%")

                     ),
                     mainPanel(
                       h4(strong("Plot Area")),
                       plotOutput("Plotting"),
                       DT::dataTableOutput("setup"),
                       h4(strong("Area for Ratio Distribution Plots")),
                       plotOutput("Plotting2")
                     )
                   )
                 )
        )},# tabItem

        ## Discovery of Changes
        {tabItem(tabName = "Biomarkers",
                fluidPage(
                  titlePanel(strong("Discovery of Changes")),
                  sidebarLayout(
                    position = "left",
                    sidebarPanel(
                      p(strong("Settings for finding significantly changed proteins")),
                      selectInput(inputId = "select_group",
                                  label = "Select group",
                                  choices = ""),
                      textInput("R_cutoff", "Set ratio cutoff",
                                value=1.4),
                      textInput("p_cutoff", "Set p-value cutoff",
                                value=0.05),
                      actionButton(inputId = "upload_cutoff",label = "Submit cutoff settings",
                                   icon=icon("upload"),width="100%"),
                      downloadButton("downloadData3", label="Download Significantly Changed Data",
                                     icon=icon("download")),
                      selectInput(inputId = "plotType2",
                                  label = "Select plot type:",
                                  choices = c("Valcano Plot",
                                              "Intensity curve with changes highlighted",
                                              "Plot for Up-regulated","Plot for Down-regulated","Gene Ontology (Accession)",
                                              "Gene Ontology (ProteinID)")),
                      helpText("*For up-/down-regulated proteins plot only:"),
                      textInput("TOPx",label = "Assign how many proteins shown in the plot:",value = 50),
                      actionButton("plot3",label="Plot",icon=icon("paint-brush"),width="100%"),
                      sliderInput("sliderwid3","Plot width",
                                  min = 4,max = 20,value = 6),
                      sliderInput("sliderhei3","Plot height",
                                  min = 4,max = 20,value = 4),
                      downloadButton("downloadPlot3", label="Download Current Plot",
                                     icon=icon("download"))

                    ),
                    mainPanel(
                      h4(strong("Table Area")),
                      DT::dataTableOutput("sign_contents"),
                      h4(strong("Plot Area")),
                      plotOutput("Plotting3")
                    )
                  )
                )
        ) #tabItem
        },

   #Re-Verification
   {tabItem(tabName = "Verify",
            fluidPage(
              titlePanel(strong("Re-verification")),
              sidebarLayout(
                position = "left",
                sidebarPanel(
                  fileInput("veri_file1", "Repload Protein Quantification result (.csv):",
                            accept=c("text/csv",
                                     "text/comma-separated-values,text/plain",
                                     ".csv")),
                  fileInput("veri_file2", "Repload Peptide Quantification result (.csv):",
                            accept=c("text/csv",
                                     "text/comma-separated-values,text/plain",
                                     ".csv")),
                  tags$hr(),
                  actionButton(inputId = "veri_submit",label = "Submit Protein and Peptide Outputs",icon=icon("upload"),width="100%"),
                  textOutput("veri_notice1"),
                  helpText("*Note: double-check if the groups(columns) in both protein and peptide files are with the same order."),
                  actionButton(inputId = "veri_inge",label = "Start Integration",icon=icon("pencil"),width="100%"),
                  helpText("A notaion will pop out after completion:"),
                  br(),
                  textOutput("veri_notice2"),
                  downloadButton("veri_downloadData1", label="Download Integrated Quantity Results", icon=icon("download")),
                  br(),
                  tags$hr(),

                  helpText("Please fill the protein accession you want to see (case sensitive):"),
                  #  selectInput(inputId = "ctrlGroup", label = "Assign control group", choices = " "),
                  textInput(inputId = "veri_accession",
                            label = "Protein Accession", value="ABCD01234"),
                  helpText("The legend won't show in the plot area if the number of peptide is bigger than 5."),
                  helpText("The first bar in each group is the protein ratio value."),
                  helpText("The download one will contain the legends. Larger width and height values recommended."),
                  actionButton("veri_visual",label="Show Target Protein Accession and Its Peptides",icon=icon("image"),width="100%"),
                  br(),
                  sliderInput("veri_sliderwid1","Plot width",
                              min = 10,max = 30,value = 15),
                  sliderInput("veri_sliderhei1","Plot height",
                              min = 10,max = 30,value = 15),
                  downloadButton("veri_downloadPlot1", label="Download Current Plot with legends", icon=icon("download"),width="100%")
                ),
                mainPanel(
                  h4(strong("Plot Area")),
                  plotOutput("Veri_plot")
                )
              )
            )
   )} # tabItem


      ) # tabItems
        ) #dashboardBody
      ) #dashboardPage
